version: "3.8"

services:
  postgres:
    image: postgres:13-alpine
    container_name: movie-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: filmboxdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  serviceregistry:
    image: "confidencedev/filmbox-svcregistry"
    container_name: serviceregistry
    ports:
      - "8761:8761"
    depends_on:
      - postgres
  cloudgateway:
    image: "confidencedev/filmbox-apigateway"
    container_name: cloudgateway
    ports:
      - "9090:9090"
    depends_on:
      - serviceregistry
  movieservice:
    image: "confidencedev/filmbox-movieservice"
    container_name: movieservice
    ports:
      - "8082:8082"
    depends_on:
      - cloudgateway

volumes:
  postgres_data:
    driver: local
