version: "3.8"

services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: filmboxdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  serviceregistry:
    image: "confidencedev/filmbox-svcregistry"
    container_name: serviceregistry
    ports:
      - "8761:8761"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test:
        ["CMD-SHELL", "curl -f http://localhost:8761/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
  cloudgateway:
    image: "confidencedev/filmbox-apigateway"
    container_name: cloudgateway
    ports:
      - "9090:9090"
    environment:
      - EUREKA_SERVER_ADDRESS=http://serviceregistry:8761/eureka
    depends_on:
      serviceregistry:
        condition: service_healthy
    healthcheck:
      test:
        ["CMD-SHELL", "curl -f http://localhost:9090/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
  movieservice:
    image: "confidencedev/filmbox-movieservice"
    container_name: movieservice
    ports:
      - "8082:8082"
    environment:
      - EUREKA_SERVER_ADDRESS=http://serviceregistry:8761/eureka
      - DB_URL=jdbc:postgresql://postgres:5432/filmboxdb
    depends_on:
      cloudgateway:
        condition: service_healthy
    healthcheck:
      test:
        ["CMD-SHELL", "curl -f http://localhost:8082/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
